# Generated by Django 2.2.6 on 2019-10-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebida_desejada', models.CharField(max_length=20)),
                ('marca_desejada', models.CharField(max_length=20)),
                ('quant_desejada', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
