# Generated by Django 2.2.6 on 2019-10-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20191030_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientes',
            new_name='Cliente',
        ),
    ]
