# Generated by Django 2.2.6 on 2019-10-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20191030_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='Model',
            old_name='bebida_desejada',
            new_name='bebida',
        ),
    ]
